### ISSUE TITLE
Custom external sources

### ISSUE THREAD

**Issue by NigoroJr** [b4b4r07/zplug2#12]
I would first like to start off by apologizing the dirtiness of the code: 1, the naming is not the best (TODO#1), 2, the style may not be the most pleasing, 3, no tests :cry: (TODO#5), and 4, since this is **just demonstrating an idea** it doesn't integrate very well with the existing code (yet) (TODO#2) nor does it have a complete set of sub commands. Allow me to explain this POC.
## Motivation

Currently, zplug officially supports github, gist, github release, bitbucket, and oh-my-zsh. However, in terms of implementation, oh-my-zsh is treated somewhat differently than the other four sources. Having bits of oh-my-zsh code here and there in the code base can be troublesome, and with the anticipated support for prezto in v2, there is a need for a more generalized approach to those external sources.
## What this proposal is

The objective of this proposal is to allow developers (and users, if they want to) to add custom sources that behave differently than the "default." For example, prezto, oh-my-zsh apply to these sources.

~~https://github.com/NigoroJr/zplug2/commit/38cef6c2ae738d54b052fa9e829ab26639cb7101~~
Edit: Development is currently done on the [external-source branch](https://github.com/NigoroJr/zplug2/tree/external-source)

The commit above has a demo external source, `gist-alt`, which simply adds the functionality of adding an executable permission to the file specified when installing from gist. Basically, zplug checks if a package is from a custom external source when it is added (in `__add__`). When installing that package, zplug checks if `__zplug::gist-alt::install` (replace `gist-alt` with the name of the custom source) is defined, and if it is, leaves the installation step up to that function which in this case clones from gist and adds the executable permission. Sample usage:

``` zsh
zplug 'foo/12345abcdf', from:gist-alt, as:command, use:baz
```

Similar thing is done for `load` and `check`; however, not for `clean`, `status` or any other sub commands (TODO#7).

Since it is difficult in zsh to pass around multiple pieces of information while maintaining a specific data structure, the argument to these callback functions are re-parsed using `__parser__` (TODO#3). I am looking for a better way to do this.
# TODOs

With that, some future works that I think need be done:
- [x] 1. Figure out a naming convention for the callback functions and ~~what this feature is called (currently "external," but I'm still trying to come up with a better name)~~ maybe third-party?
- [x] ~~2. Make helper functions such as `__default_install`, `__default_check`, or `__default_load`, so that callback functions can use them if necessary and also so that default sources can use them (rather than having to do `[[ -d $zspec[dir] ]]` every time~~
- [x] 3. Passing of the package information (i.e. `$zspec`).
- [x] 4. Create `oh-my-zsh` custom source.
- [ ] 5. Tests
- [x] 6. Consistent way of checking for external callback existence and calling it
- [x] 7. Other sub commands
- [x] 8. `s/callback/handler/g`

Any input is most welcomed :eyes:

**Comment by babarot** [comment]
@NigoroJr Many thanks :coffee: :coffee: :coffee: 

Your proposal was impressive! Indeed, the implementation of OMZ had been scattered in various commands. Because of that, we were difficult to do other implementations.Your **external** function will make us easy to implement other features. Please keep up the good work, thanks.

**Comment by NigoroJr** [comment]
@b4b4r07 I noticed there are several places that use `local -A zspec`.

``` console
$ grep -n 'local -A zspec' **(.)
autoload/commands/__check__:10:local -A zspec
autoload/commands/__clean__:9:local -A zspec
autoload/commands/__install__:11:local -A zspec
autoload/commands/__load__:10:local -A zspec
autoload/commands/__status__:11:local -A zspec
autoload/commands/__update__:68:        local -A zspec
autoload/utils/__validator__:5:local -A zspec
lib/core/core.zsh:15:    local -A zspec
```

Do you think it's a bad/risky decision to make a global hash that contains the information (e.g. `use`, `name`, `from`) for the one package that zplug is currently looking at? I'm thinking of something that is just like the `typeset -gx -A zplugs` in `lib/zplug/variables.zsh` except that it's going to be for one package. The reason I ask this is because it will make it easier for external sources to access information regarding the package.

Example:
Now:

``` zsh
# In __load__
# Pass the package info in one line
__zplug::foo-source::load "$line"
```

``` zsh
# and parse that in foo-source.zsh
__zplug::foo-source::load() {
    local -A zspec=( ${(@f)"$(__parser__ "$line")"} )

    # use zspec
}
```

With global `zspec`:

``` zsh
# In __load__
# Simply make a call (zspec is already set)
__zplug::foo-source::load
```

``` zsh
# In foo-source.zsh
__zplug::foo-source::load() {
    # immediately start using zspec
}
```

Another benefit comes from the external source being able to modify the `zspec` information, which can then be used in the callee. For example, there needs to be [special operations](https://github.com/b4b4r07/zplug2/blob/f2b2bc8f1866de09b1711919862c5ff6be7324d5/autoload/utils/__add__#L86) for oh-my-zsh regarding the `dir` tag. By letting the external source handle this operation, the callee simply needs to add the correctly modified `zspec` to `zspecs`.

Of course, there is some risk associated with assuming that `zspec` is set before it's used and the double-edged sword of allowing modifications to be done on the package info, so I wanted to ask for your opinion.

**Comment by NigoroJr** [comment]
Closing this issue since #17 was merged.

**Comment by babarot** [comment]
:coffee:
