### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by babarot** [b4b4r07/zplug2#5]
- [ ] More tests
  - [x] https://github.com/b4b4r07/zplug2/blob/master/test/autoload/commands/__install___test.zsh
  - [x] https://github.com/b4b4r07/zplug2/blob/master/test/autoload/commands/__load___test.zsh
  - [ ] https://github.com/b4b4r07/zplug2/blob/master/test/autoload/commands/__status___test.zsh
  - [x] https://github.com/b4b4r07/zplug2/blob/master/test/autoload/commands/__update___test.zsh
  - [ ] https://github.com/b4b4r07/zplug2/blob/master/test/autoload/utils/__self___test.zsh
  - [x] ~~https://github.com/b4b4r07/zplug2/blob/master/test/autoload/utils/__validator___test.zsh~~
  - [ ] https://github.com/b4b4r07/zplug2/blob/master/test/autoload/autoload_test.zsh
  - [ ] https://github.com/b4b4r07/zplug2/blob/master/test/autoload/init_test.zsh
  - [ ] https://github.com/b4b4r07/zplug2/blob/master/test/autoload/zplug_test.zsh
  - [ ] `lib/*`
- [x] Implement `status` command
- [ ] Update `zplug.txt` (`of`, `file` tag)

**Comment by NigoroJr** [comment]
- [x] More informative messages (for example, it only says that there was at least one package that failed to `install` but doesn't say which package it was)
- [x] b4b4r07/zplug#118
- [x] external source for prezto b4b4r07/zplug#76
